blog/authe/urls.py
from django.urls import path
from .views import Register, Login, Index, Fail, signout
from . import views

app_name = 'authe'

urlpatterns = [
    path('', Register.as_view(), name = 'register'),
    path('login/', Login.as_view(), name='login'),
    path('', Index.as_view(), name='index'),
    path('fail/', Fail.as_view(), name='fail'),
    path('signout/', signout, name='signout'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authe.urls')),
    path('blog_app', include('blog_app.urls')),
]

blog/blog_app/urls.py
from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.ViewAllBlogs.as_view(), name='index'),
    path('create/', views.CreateBlogView.as_view(), name='create'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('edit/<int:blog_id>/', views.EditBlog.as_view(), name='edit'),
    path('delete/<int:blog_id>/', views.DeleteBlog.as_view(), name='delete'),
]

blog/authe/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    email = models.EmailField(unique=True)
    full_name = models.CharField(max_length=100)

    def __str__(self):
        return self.username

blog/blog_app/models.py
from django.db import models
from authe.models import User

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField(null=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def to_json(self):
        return {
            'title': self.title,
            'content': self.content,
        }

blog/authe/forms.py
from django import forms # importing forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from .models import User


class UserSignUpForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs['placeholder'] = 'Введите пароль'
        self.fields['password2'].widget.attrs['placeholder'] = 'Подтвердите пароль'


    class Meta: 
        model = User
        fields = ('username','email', 'full_name', 'password1', 'password2')

        widgets = {
            'email': forms.TextInput(attrs={'placeholder': 'Введите email'}),
            'full_name': forms.TextInput(attrs={'placeholder': 'Введите полное имя'}),
            'username': forms.TextInput(attrs={'placeholder':'Введите имя пользователя'})
            }


class UserSignInForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Введите имя пользователя'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Введите пароль'}))

blog/blog_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from .models import Blog

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content']

        widgets = {
            'title': forms.TextInput(attrs={'placeholder':'Введите заголовок блога'}),
            'content': forms.Textarea(attrs={'placeholder':'Введите описание блога'})
        }
        

blog/authe/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import login, logout, authenticate
from django.urls import reverse_lazy
from .forms import UserSignUpForm, UserSignInForm



class Register(View): # для регистрации
    def get(self, request):
        form = UserSignUpForm()
        context = {'form': form}
        return render(request, 'authe/register.html', context=context)

    def post(self, request):
        form = UserSignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('authe:login'))
        else:
            context = {'form': form}
            return render(request, 'authe/register.html', context=context)


class Login(View): # для логина
    def get(self, request):
        form = UserSignInForm()
        context = {'form':form}
        return render(request, 'authe/login.html', context=context)

    def post(self, request):
        form = UserSignInForm(request, request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse_lazy('blogs:index'))
        
        return render(request, 'authe/fail.html', context={'form': form})


class Index(View):
    def get(self, request):
        return render(request, 'authe/index.html')

class Fail(View):
    def get(self, request):
        return render(request, 'authe/fail.html')
    
def signout(request):
    logout(request)
    return redirect(reverse_lazy('authe:login'))

blog/blog_app/views.py
from django.shortcuts import render, redirect
from django.views import View # importing View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404

from .models import Blog # importing our models
from .forms import BlogForm
from authe.models import User

class ViewAllBlogs(View):   # главная
    def get(self, request):
        blogs = Blog.objects.all().order_by('-created_at')
        context = {
            'title': 'Список блогов',
            'blogs': blogs,
        }

        return render(request, 'blog_app/index.html', context=context)


class CreateBlogView(View):     # создать
    @method_decorator(login_required)
    def get(self, request):
        form = BlogForm()
        context = {'form': form}
        return render(request, 'blog_app/create.html', context=context)

    @method_decorator(login_required)
    def post(self, request):
        form = BlogForm(request.POST)
        if form.is_valid():
            blog = form.save(commit=False)
            blog.author = request.user  # Устанавливаем автора как текущего пользователя
            blog.save()
            return redirect('blogs:index')
        return render(request, 'blog_app/create.html', {'form': form})
    


class ProfileView(View):        # личный профиль
    def get(self, request):
        user = request.user
        blogs = Blog.objects.filter(author=user).order_by('-created_at')

        context = {
            'title': 'Мой профиль',
            'user': user,
            'blogs': blogs,
        }
        
        return render(request, 'blog_app/profile.html', context=context)
    

class EditBlog(View):   # редактировать
    def get(self, request, blog_id):
        blog = Blog.objects.get(id=blog_id)
        form = BlogForm(blog.to_json())

        context = {
            'title': 'Редактировать блог',
            'form': form,
            'blog': blog,
        }

        return render(request, 'blog_app/edit.html', context=context)
    
    def post(self, request, blog_id):
        blog = Blog.objects.get(id=blog_id)
        form = BlogForm(request.POST)
        if form.is_valid():   
                blog.title = request.POST['title']
                blog.content = request.POST['content']            
                blog.save()
                return redirect(reverse_lazy('blogs:index'))
        else:
            context = {
                'title': 'Редактировать блог',
                'form': form,
                'blog': blog,
                'error': 1,
            }
            return render(request, 'blog_app/edit.html', context=context)


class DeleteBlog(View): # удаление
    def get(self, request, blog_id):
        blog = Blog.objects.get(id=blog_id)
        blog.delete()

        return redirect(reverse_lazy('blogs:profile'))

blog/authe/templates/authe/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} ... {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'authe/styles/authe.css' %}">
    
    {% block static %}
        
    {% endblock %}
    
</head>

<body>
    <header class="header">

        <a href="{% url 'blogs:index' %}" class="title"> Decode Blog </a>

        <div class="search-bar">
            <input type="text" id="search-input" placeholder="Поиск по блогам">
            <button type="submit" class="search-button">Найти</button>
        </div>
            <div class="btns">     
                {% if request.user and request.user.is_authenticated %} 
                    <a href="{% url 'blogs:create' %}" class="register btn btn-primary"> Создать </a>
                    <a href="{% url 'authe:signout' %}" class="logout btn btn-primary">Выйти</a>
                    <a href="{% url 'blogs:profile' %}" class="register btn btn-primary">Профиль</a>
                {% else %}
                    <a href="{% url 'authe:register' %}" class="register btn btn-primary"> Регистрация </a>
                    <a href="{% url 'authe:login' %}" class="login btn btn-primary"> Вход </a>
                {% endif %}
            </div>
    </header>

    {% block content %}
    {% endblock %}

</body>
</html>

blog/authe/templates/authe/fail.html
{% extends 'authe/base.html' %}
{% block title %} Ошибка авторизации {% endblock %}

{% block content %}
    <style>
        .center-content {
            text-align: center;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 75vh; /* Центрирование по вертикали */
        }
    </style>

    <div class="center-content"> 
        <h1>Ошибка авторизации</h1>
        <p>Извините, вы ввели неверные учетные данные. Пожалуйста, попробуйте снова.</p>
        <p>Вернуться на страницу авторизации <a href="{% url 'authe:login' %}">Вернуться</a></p>
    </div>
{% endblock %}

blog/authe/templates/authe/login.html
{% extends "authe/base.html" %}

{% block title %}Войти{% endblock %}

{% load static %}

{% block static %}
    <link rel="stylesheet" href="{% static 'authe/styles/forms.css' %}">        
{% endblock %}

{% block content %}
<form method="post" class="form-signin" style="display: flex; align-items: center; flex-direction: column;padding-top: 250px;">
  {% csrf_token %}
    {% for f in form %}
      {{ f }}
  {% endfor %}
    <button type="submit" class="btn btn-dark">Войти</button>
    <p class="mt-1">Нет аккаунта? <a href="{% url 'authe:register' %}">Зарегистрироваться</a></p>
  </form>
{% endblock %}

blog/authe/templates/authe/register.html
{% extends 'authe/base.html' %}
{% block title%} Зарегистрироваться {% endblock %}

{% load static %}

{% block static %}
    <link rel="stylesheet" href="{% static 'authe/styles/forms.css' %}">        
{% endblock %}


{% block content %}
    <div class="form-wrapper">
        <form method="post" class="form-signin" style="display: flex; align-items: center; flex-direction: column;padding-top: 250px;">
            {% csrf_token %}
            {% for f in form %}
                {{ f }}
            {% endfor %}
            <button type="submit" class="btn btn-dark"> Зарегистрироваться </button>
            <p class="mt-1">Есть аккаунт? <a href="{% url 'authe:login' %}">Войти</a></p>
        </form>
    </div>

{% endblock %}

blog/blog_app/templates/blog_app/create.html
{% extends "authe/base.html" %}
{% load static %}
{% block title %} Создание блога {% endblock %}

{% block static %}
    <link rel="stylesheet" href="{% static 'blog_app/styles/create.css' %}">
{% endblock %}


{% block content %}
    <div class="create-blog-container">
        <h2 class="mt-3">Создание блога</h2>
        <form method="post" class="create-blog-form">
            {% csrf_token %}
            {% for f in form %}
                {{ f }}
            {% endfor %}
            <button type="submit" class="create-blog-button">Создать блог</button>
        </form>
        <a href="{% url 'blogs:index' %}" class="back-to-blog btn btn-dark">Назад к блогам</a>
    </div>
{% endblock %}

blog/blog_app/templates/blog_app/edit.html
{% extends 'authe/base.html' %}
{% load static %}
{% block title %}Редактировать блог{% endblock %}

{% block static %} 
<link rel="stylesheet" href="{% static 'blog_app/styles/edit.css' %}">
{% endblock %}

{% block content %}
  <div class="container">
    <h1>{{ title }}</h1>

    <form action="{% url 'blogs:edit' blog.id %}" method="post" class="blog-form">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Сохранить изменения</button>
        {% if error %}
            Error: {{error}}
        {% endif %}
    </form>
  </div>
{% endblock %}

blog/blog_app/templates/blog_app/index.html
{% extends "authe/base.html" %}
{% load static %}

{% block title %} Главная страница {% endblock %}

{% block static %}
    <link rel="stylesheet" href="{% static 'blog_app/styles/blog.css' %}">
{% endblock %}


{% block content %}



    <section class="entire">    
        <div class="blog-list">
            {% for b in blogs %}
                <div class="blog-item">
                    <h2>{{ b.title }}</h2>
                    <p><strong>Автор:</strong> {{ b.author.username }}</p>
                    <p><strong>Дата создания:</strong> {{ b.created_at|date:"d.m.Y H:i:s" }}</p>
                    <div class="blog-content">
                        {{ b.content|linebreaks }}
                    </div>
                    {% if b.author.is_superuser %}
                        <p class="developer-blog">Блог разработчика</p>
                    {% else %}
                        <p class="user-blog">Пользовательский блог</p>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}

blog/blog_app/templates/blog_app/profile.html
<!-- blog_app/templates/blog_app/user_profile.html -->
{% extends 'authe/base.html' %}
{% load static %}

{% block static %}
    <link rel="stylesheet" href="{% static 'blog_app/styles/profile.css' %}">        
{% endblock %}

{% block title %} Личный кабинет {% endblock %}

{% block content %}
    <div class="container">
        <h1>{{ title }}</h1>

        <div class="profile-info">
            <p>Email: {{ user.email }}</p>
            <p>Full Name: {{ user.full_name }}</p>
        </div>

        <h2> Мои блоги: </h2>

        <div class="blog-form">
            {% for blog in blogs %}
                <div class="blog-item">
                    <p class="blog-title">{{ blog.title }}</p>
                    <p class="blog-content">{{ blog.content }}</p>
                    <p class="blog-date">{{ blog.created_at }}</p>
                    <div class="edit-del">
                        <a href="{% url 'blogs:edit' blog.id %}" class="edit--btn"> Редактировать </a>
                        <a href="{% url 'blogs:delete' blog.id %}" class="delete--btn"> Удалить </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}